
from __future__ import annotations
from datetime import datetime,date,time,timedelta
from typing import Literal, List, Optional
from pydantic import BaseModel, EmailStr, Field, ConfigDict
from app.models.people import AccountTypeEnum,ShiftTypeEnum,GenderEnum


# Staff roles (includes your new admins + front office)
StaffRole = Literal[
    "receptionist",
    "front_office",
    "pharmacist",
    "pathologist",
    "radiologist",
    "accountant",
    "nurse",
    "admin",
    "branch_admin",
    "pharmacy_admin",
    "pathology_admin",
    "radiology_admin",
]

Gender = Literal["Male", "Female", "Other"]
BloodGroup = Literal["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]
MaritalStatus = Literal["Single", "Married", "Divorced", "Widowed"]

class PatientCreateIn(BaseModel):
    first_name: str
    last_name: str | None = None
    dob: date | None = None
    phone_number: str | None = None

    # NEW FIELDS
    guardian_name: str | None = None
    gender: Gender | None = None
    age: int | None = None                                 # keep even if dob is present
    blood_group: BloodGroup | None = None
    marital_status: MaritalStatus | None = None
    email: EmailStr | None = None
    location: str | None = None
    reason: str | None = None

    aadhaar_no: str | None = Field(default=None, min_length=4, max_length=20)
    # Aadhaar file path will be stored by router -> service as string

class PatientOut(BaseModel):
    id: int
    first_name: str
    last_name: str | None = None
    patient_code: str | None = None
    phone_number: str | None = None
    # Optional: expose the new fields (uncomment as you need them in UI)
    guardian_name: str | None = None
    gender: Gender | None = None
    age: int | None = None
    blood_group: BloodGroup | None = None
    marital_status: MaritalStatus | None = None
    email: EmailStr | None = None
    location: str | None = None
    reason: str | None = None
    aadhaar_no: str | None = None
    aadhaar_file_path: str | None = None

    class Config:
        from_attributes = True



class DoctorCreateIn(BaseModel):
    first_name: str
    last_name: str | None = None

    consultation_fee: int = Field(default=0, ge=0)
    specialty: str | None = None
    doctor_code: Optional[str] = None
    designation: Optional[str] = None
    specialization: Optional[str] = None
    experience: Optional[int] = None
    department: str

    # Staff required fields
    email: EmailStr
    phone: str
    gender: GenderEnum
    date_of_birth: date
    emergency_contact_name: str
    emergency_contact_number: str
    address_city: str
    address_state: str
    address_pincode: str
    joining_date: date
    qualification: str
    monthly_salary: float
    shift_type: ShiftTypeEnum
    shift_start: Optional[str] = None
    shift_end: Optional[str] = None
    pan_number: str
    aadhar_number: str
    bank_account_holder_name: str
    bank_account_number: str
    bank_ifsc_code: str
    bank_name: str

    # Optional doctor/staff fields
    uan_number: Optional[int] = None
    esi_number: Optional[str] = None
    pan: Optional[str] = None
    aadhar: Optional[str] = None
    bank: Optional[str] = None
    account_no: Optional[str] = None
    ifsc: Optional[str] = None
    floor_location: Optional[str] = None

    create_user: bool = False
    password: str | None = None



class DoctorOut(BaseModel):
    id: int
    doctor_code: str | None = None
    first_name: str
    last_name: str | None = None
    staff_id: Optional[int] = None
    staff_code: str | None = None
    user_id: int | None = None
    profile_pic_url: Optional[str] = None
    consultation_fee: Optional[int] = None
    specialty: Optional[str] = None
    designation: Optional[str] = None
    department: str
    specialization: Optional[str] = None
    signature_url: Optional[str] = None
    license_url: Optional[str] = None
    uan_number: Optional[int] = None
    esi_number: Optional[str] = None
    pan: Optional[str] = None
    aadhar: Optional[str] = None
    bank: Optional[str] = None
    account_no: Optional[str] = None
    ifsc: Optional[str] = None
    floor_location: Optional[str] = None
    qualification: Optional[str] = None
    gender: Optional[GenderEnum] = None
    email: Optional[EmailStr] = None
    phone_number: Optional[str] = None
    date_of_birth: Optional[date] = None
    address_city: str| None = None
    address_street: str| None = None
    address_state: str| None = None
    address_pincode: str | None = None
    address_country: str| None = None
    experience: float | None = None

    model_config = ConfigDict(from_attributes=True)

class StaffCreateIn(BaseModel):
    # Auto-generated by backend
    employee_id: Optional[str] = None
    staff_code: Optional[str] = None
    user_id: Optional[int] = None

    # Personal
    first_name: str
    last_name: Optional[str] = None
    full_name: Optional[str] = None

    email: EmailStr
    phone_number: str
    gender: GenderEnum
    date_of_birth: date
    emergency_contact_name: str
    emergency_contact_number: str

    # Address
    address_street: Optional[str] = None
    address_city: str
    address_state: str
    address_pincode: str
    address_country: str = "India"

    # Employment
    department: str
    designation: str
    joining_date: date
    role: str = "EMPLOYEE"

    # Qualification
    qualification: str
    experience_years: float = 0.0

    # Shift
    shift_type: ShiftTypeEnum = ShiftTypeEnum.FLEXIBLE
    shift_start: Optional[str] = None
    shift_end: Optional[str] = None

    # Salary
    monthly_salary: float

    # IDs
    pan_number: str
    aadhar_number: str
    uan_number: Optional[str] = None
    esi_number: Optional[str] = None

    # Bank
    bank_account_holder_name: str
    bank_account_number: str
    bank_ifsc_code: str = Field(
        ...,
        min_length=11,
        max_length=11,
        description="IFSC code must be exactly 11 characters"
    )
    bank_name: str
    bank_branch_name: Optional[str] = None
    bank_account_type: AccountTypeEnum = AccountTypeEnum.SAVINGS

    create_user: bool = False
    password: Optional[str] = None

    is_active: bool = True


# =========================================================
# STAFF UPDATE
# =========================================================

class StaffUpdate(BaseModel):
    employee_id: Optional[str] = None
    staff_code: Optional[str] = None
    user_id: Optional[int] = None

    first_name: Optional[str] = None
    last_name: Optional[str] = None
    full_name: Optional[str] = None

    email: Optional[EmailStr] = None
    phone_number: Optional[str] = None
    gender: Optional[GenderEnum] = None
    date_of_birth: Optional[date] = None
    emergency_contact_name: Optional[str] = None
    emergency_contact_number: Optional[str] = None

    address_street: Optional[str] = None
    address_city: Optional[str] = None
    address_state: Optional[str] = None
    address_pincode: Optional[str] = None
    address_country: Optional[str] = "India"

    department: Optional[str] = None
    designation: Optional[str] = None
    joining_date: Optional[date] = None
    role: Optional[str] = None

    qualification: Optional[str] = None
    experience_years: Optional[float] = None

    shift_type: Optional[ShiftTypeEnum] = None
    shift_start: Optional[str] = None
    shift_end: Optional[str] = None

    monthly_salary: Optional[float] = None

    pan_number: Optional[str] = None
    aadhar_number: Optional[str] = None
    uan_number: Optional[str] = None
    esi_number: Optional[str] = None
    password: Optional[str] = None

    bank_account_holder_name: Optional[str] = None
    bank_account_number: Optional[str] = None
    bank_ifsc_code: Optional[str] = None
    bank_name: Optional[str] = None
    bank_branch_name: Optional[str] = None
    bank_account_type: Optional[AccountTypeEnum] = None


# =========================================================
# STAFF RESPONSE
# =========================================================

class StaffResponse(BaseModel):
    model_config = {"from_attributes": True}

    # System
    id          : int
    branch_id   : int

    employee_id : str
    staff_code  : Optional[str]
    user_id     : Optional[int]

    is_active   : bool
    created_at  : datetime
    updated_at  : datetime

    # Personal
    first_name : str
    last_name  : Optional[str]
    full_name  : str

    email                    : str
    phone_number             : str
    gender                   : GenderEnum
    date_of_birth            : date
    emergency_contact_name   : str
    emergency_contact_number : str

    # Address
    address_street  : Optional[str]
    address_city    : str
    address_state   : str
    address_pincode : str
    address_country : str

    # Employment
    department   : str
    designation  : str
    joining_date : date
    role         : str

    # Qualification
    qualification    : str
    experience_years : float

    # Shift
    shift_type  : Optional[ShiftTypeEnum]
    shift_start : Optional[str]
    shift_end   : Optional[str]

    # Salary
    monthly_salary : float

    # IDs
    pan_number    : str
    aadhar_number : str
    uan_number    : Optional[str]
    esi_number    : Optional[str]

    # Bank
    bank_account_holder_name : str
    bank_account_number      : str
    bank_ifsc_code           : str
    bank_name                : str
    bank_branch_name         : Optional[str]
    bank_account_type        : AccountTypeEnum

    # Documents
    id_proof_url          : Optional[str]
    id_proof_filename     : Optional[str]
    id_proof_type         : Optional[str]
    id_proof_uploaded_at  : Optional[datetime]

    address_proof_url          : Optional[str]
    address_proof_filename     : Optional[str]
    address_proof_type         : Optional[str]
    address_proof_uploaded_at  : Optional[datetime]

    educational_certificates_urls      : Optional[str]
    educational_certificates_filenames : Optional[str]

    experience_letters_urls      : Optional[str]
    experience_letters_filenames : Optional[str]

    profile_photo_url          : Optional[str]
    profile_photo_filename     : Optional[str]
    profile_photo_uploaded_at  : Optional[datetime]

    signature_url          : Optional[str]
    signature_filename     : Optional[str]
    signature_uploaded_at  : Optional[datetime]


# =========================================================
# STAFF LIST RESPONSE
# =========================================================

class StaffListResponse(BaseModel):
    model_config = {"from_attributes": True}

    id            : int
    employee_id   : str
    staff_code    : Optional[str]

    first_name    : str
    last_name     : Optional[str]
    full_name     : str

    email         : str
    phone_number  : str

    department    : str
    designation   : str
    joining_date  : date

    role          : str
    is_active     : bool

class StaffOut(BaseModel):
    staff_id: int
    staff_code: str | None = None
    role_name: str
    user_id: int | None = None
    model_config = ConfigDict(from_attributes=True)
# --- Users (raw) ---

class UserCreateIn(BaseModel):
    email: EmailStr
    password: str
    phone: str | None = None
    roles: List[str]  # e.g., ["doctor", "branch_admin"]

class UserOut(BaseModel):
    id: int
    email: EmailStr
    is_active: bool
    roles: list[str]
    hospital_id: int | None = None
    branch_id: int | None = None
